### ISSUE TITLE
Document how to get nix develop with lsp installed

### ISSUE THREAD

**Issue by 3noch** [claymager/idris2-pkgs#5]
I'm very new to nix flakes and I'm struggling to find out how I might have a shell where idris2-lsp is available for my IDE.

**Comment by 3noch** [comment]
Adding this to `flake.nix` seems to work:

```nix
        devShell = pkgs.mkShell {
          buildInputs = [ pkgs.idris2.packages.lsp ];
          buildInputsFrom = [ mypkg ];
        };
```

**Comment by claymager** [comment]
Do you have some other overlay active? I can't find `buildInputsFrom`, but it looks useful. 

I've started using something like this, but I'm still not quite happy with it:
```nix
{
  devShell = pkgs.mkShell {
    buildInputs = [
      (pkgs.idris2.packages.lsp.withPackages (p: mypkg.idrisLibraries))
    ];
}
```

**Comment by 3noch** [comment]
I mistyped. It's actually `inputsFrom`: https://nixos.org/manual/nixpkgs/stable/#sec-pkgs-mkShell

**Comment by claymager** [comment]
Current approach, as in the [new project tutorial](https://github.com/claymager/idris2-pkgs/blob/main/docs/new-project.rst), is to use

```nix
{
  buildInputs = [ (idris2-pkgs._builders.devEnv mypkg) ];
}
```
